<?php

use Illuminate\Database\Seeder;

class ConsumersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Consumer::truncate();

        /**/
        \App\Models\Consumer::create([
            'id' => 1,
            'consumer_code' => 'admin',
            'IsAdmin' => 1,
            'consumer_login' => 'admin',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Администратор',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 1,
            'email' => 'admin@admin.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 2,
            'consumer_code' => 'user',
            'IsAdmin' => 2,
            'consumer_login' => 'user',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Пользователь',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'user@user.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 3,
            'consumer_code' => 'manager',
            'IsAdmin' => 3,
            'consumer_login' => 'manager',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Менеджер',
            'remember_token' => 'ccHwjPYh00pMmW6dBKOPmrl6nIe9mYAzcuOAbBIoeXtjlgfqHAFF2NLuGivV',
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'manager@manager.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 4,
            'consumer_code' => 'seed',
            'IsAdmin' => 1,
            'consumer_login' => 'seed',
            'password' => '',
            'consumer_name' => 'Для предопределенных данных',
            'remember_token' => NULL,
            'consumer_status_n' => 4,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'seed@seed.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 5,
            'consumer_code' => '1c',
            'IsAdmin' => 1,
            'consumer_login' => '1c',
            'password' => '',
            'consumer_name' => 'Обмен с 1С',
            'remember_token' => NULL,
            'consumer_status_n' => 4,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => '1c@1c.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 6,
            'consumer_code' => 'RblAdminDev',
            'IsAdmin' => 1,
            'consumer_login' => 'RblAdminDev',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Росбанк Администратор Разработчик',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 1,
            'email' => 'RblAdminDev@RblAdminDev.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 7,
            'consumer_code' => 'RblManagerDev',
            'IsAdmin' => 3,
            'consumer_login' => 'RblManagerDev',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Росбанк Менеджер Разработчик',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'RblManagerDev@RblManagerDev.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 8,
            'consumer_code' => 'RblUserDev',
            'IsAdmin' => 2,
            'consumer_login' => 'RblUserDev',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Росбанк Пользователь Разработчик',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 2,
            'email' => 'RblUserDev@RblUserDev.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 9,
            'consumer_code' => 'RblAdmin',
            'IsAdmin' => 1,
            'consumer_login' => 'RblAdmin',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Росбанк Администратор',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 1,
            'email' => 'RblAdmin@RblAdmin.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 10,
            'consumer_code' => 'RblManager',
            'IsAdmin' => 3,
            'consumer_login' => 'RblManager',
            'password' => '$2y$10$aTtxqL7b1GMkhsB92zdile0JmcruZX.XawBf7tCTEwhIiW1CmqOli',
            'consumer_name' => 'Росбанк Менеджер',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'RblManager@RblManager.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 11,
            'consumer_code' => 'RblUser',
            'IsAdmin' => 2,
            'consumer_login' => 'RblUser',
            'password' => '$2y$10$aTtxqL7b1GMkhsB92zdile0JmcruZX.XawBf7tCTEwhIiW1CmqOli',
            'consumer_name' => 'Росбанк Пользователь',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'RblUser@RblUser.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            //            'photo' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 12,
            'consumer_code' => 'RblUser2',
            'IsAdmin' => 2,
            'consumer_login' => 'RblUser2',
            'password' => '$2y$10$aTtxqL7b1GMkhsB92zdile0JmcruZX.XawBf7tCTEwhIiW1CmqOli',
            'consumer_name' => 'Росбанк Пользователь',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'RblUser2@RblUser2.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-05-03 14:00:00',
            'updated_at' => '2019-05-03 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 13,
            'consumer_code' => 'LtManager',
            'IsAdmin' => 3,
            'consumer_login' => 'LtManager',
            'password' => '$2y$10$s58/YPkuiz399X.4oMeLn.qkbhIM8DR3mZhNGcAgeYXk3maLBXDiS',
            'consumer_name' => 'Менеджер',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'LtManager@LtManager.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 14,
            'consumer_code' => 'LtUser',
            'IsAdmin' => 2,
            'consumer_login' => 'LtUser',
            'password' => '$2y$10$s58/YPkuiz399X.4oMeLn.qkbhIM8DR3mZhNGcAgeYXk3maLBXDiS',
            'consumer_name' => 'Пользователь с одним контрагентом',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'LtUser@LtUser.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => 'Иван',
            'last_name' => 'Иванов',
            'middle_name' => 'Иванович',
            'male_l' => NULL,
            'birth_date' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 15,
            'consumer_code' => 'LtUser2',
            'IsAdmin' => 2,
            'consumer_login' => 'LtUser2',
            'password' => '$2y$10$s58/YPkuiz399X.4oMeLn.qkbhIM8DR3mZhNGcAgeYXk3maLBXDiS',
            'consumer_name' => 'Пользователь c несколькими контрагентами',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'LtUser2@LtUser2.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => 'Петр',
            'last_name' => 'Петров',
            'middle_name' => 'Петрович',
            'male_l' => NULL,
            'birth_date' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-05-03 14:00:00',
            'updated_at' => '2019-05-03 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 16,
            'consumer_code' => 'LtAdmin',
            'IsAdmin' => 1,
            'consumer_login' => 'LtAdmin',
            'password' => '$2y$10$kIkp7yUlHjfVleVEO1di3uUw20J4HBFH6zHfXldtaeVLHL5nti7F.',
            'consumer_name' => 'Супер администратор',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 1,
            'email' => 'LtAdmin@LtAdmin.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => NULL,
            'last_name' => NULL,
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-05-03 14:00:00',
            'updated_at' => '2019-05-03 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        /**/
        \App\Models\Consumer::create([
            'id' => 20,
            'consumer_code' => 'BnAdmin',
            'IsAdmin' => 3,
            'consumer_login' => 'BnAdmin',
            'password' => '$2y$10$Qhi7dnlYu36oI5Hu/N/1XeI8iJaqsBCT44TafjmiR8kdmbm8/pbam',
            'consumer_name' => 'Администратор сайта BankNet',
            'remember_token' => NULL,
            'consumer_status_n' => 3,
            'consumer_type_code' => '0',
            'consumer_is_system_n' => 0,
            'email' => 'BnAdmin@banknet.com',
            'email2' => NULL,
            'phone_number' => NULL,
            'url_name' => NULL,
            'first_name' => 'Администратор',
            'last_name' => 'сайта BankNet',
            'middle_name' => NULL,
            'male_l' => NULL,
            'birth_date' => NULL,
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2019-04-15 14:00:00',
            'updated_at' => '2019-04-15 14:00:00',
            'agreement_accepted_date' => '2019-04-15 14:00:00',
        ]);


        if (config("database.default") == "pgsql")
            \Illuminate\Support\Facades\DB::statement("SELECT setval('\"public\".\"Consumers_id_seq\"', 2000, true)");

    }
}