<?php

use Illuminate\Database\Seeder;

class BlCustomerRequestTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\BL\BlCustomerRequest::truncate();

        \App\Models\BL\BlCustomerRequest::create([
            'id' => 1,
            'lessee_contractor_id' => 1,
            'bl_status_id' => 8,
            'db_area_id' => 6,
            'company_id' => 5,
            'lessee_bl_legal_form_id' => 15,
            'supplier_contractor_id' => 7,
            'supplier_bl_legal_form_id' => 10,
            'bl_customer_request_number' => '0000-000001',
            'bl_customer_request_date' => '2020-01-10 15:23:26',
            'lessee_type' => 1,
            'lessee_name' => 'Иванов И.И.',
            'lessee_second_name' => 'Иванов',
            'lessee_first_name' => 'Иван',
            'lessee_middle_name' => 'Иванович',
            'lessee_person_phone' => '+7 (903) 9876543',
            'lessee_position' => 'Менеджер',
            'lessee_email' => 'ivaniov@test.com',
            'lessee_inn' => '123456789047',
            'lessee_kpp' => null,
            'lessee_ogrn' => null,
            'lessee_legal_address' => 'Москва г, пл.Мира, дом № 22',
            'lessee_actual_address' => 'Москва г, Пушкинская, дом № 99',
            'lessee_phone' => '+7 (903) 1234567',
            'supplier_type' => 0,
            'supplier_name' => 'Audi',
            'supplier_second_name' => null,
            'supplier_first_name' => null,
            'supplier_middle_name' => null,
            'supplier_email' => null,
            'supplier_inn' => '3253530050',
            'supplier_kpp' => '177500354',
            'supplier_ogrn' => null,
            'supplier_legal_address' => null,
            'supplier_actual_address' => null,
            'supplier_person_phone' => null,
            'supplier_person_FIO' => null,
            'supplier_phone' => null,
            'supplier_position' => null,
            'uid_1c_code' => 'f32d0811-1b1b-11e9-810d-005056986dc1',
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2020-01-10 15:23:26',
            'updated_at' => '2020-01-10 15:23:26',
            'partner_point_id'  => 2,
        ]);

        \App\Models\BL\BlCustomerRequest::create([
            'id' => 2,
            'lessee_contractor_id' => 9,
            'bl_status_id' => 3,
            'db_area_id' => 6,
            'company_id' => 5,
            'lessee_bl_legal_form_id' => 6,
            'supplier_contractor_id' => 7,
            'supplier_bl_legal_form_id' => 10,
            'bl_customer_request_number' => '0000-000002',
            'bl_customer_request_date' => '2020-01-15 15:35:07',
            'lessee_type' => 1,
            'lessee_name' => 'ИП Василий В.В.',
            'lessee_second_name' => 'Васильев',
            'lessee_first_name' => 'Василий',
            'lessee_middle_name' => 'Васильевич',
            'lessee_person_phone' => null,
            'lessee_position' => null,
            'lessee_email' => null,
            'lessee_inn' => '231231346517',
            'lessee_kpp' => '750035174',
            'lessee_ogrn' => '2107104440031',
            'lessee_legal_address' => null,
            'lessee_actual_address' => null,
            'lessee_phone' => null,
            'supplier_type' => 0,
            'supplier_name' => 'Audi',
            'supplier_second_name' => null,
            'supplier_first_name' => null,
            'supplier_middle_name' => null,
            'supplier_email' => null,
            'supplier_inn' => '3253530050',
            'supplier_kpp' => '177500354',
            'supplier_ogrn' => null,
            'supplier_legal_address' => null,
            'supplier_actual_address' => null,
            'supplier_person_phone' => null,
            'supplier_person_FIO' => null,
            'supplier_phone' => null,
            'supplier_position' => null,
            'uid_1c_code' => '006d40be-3d1c-11ea-9d69-708bcda427ce',
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2020-01-15 15:35:07',
            'updated_at' => '2020-01-15 15:35:07',
            'partner_point_id'  => 1,
        ]);

        \App\Models\BL\BlCustomerRequest::create([
            'id' => 3,
            'lessee_contractor_id' => 13,
            'bl_status_id' => 10,
            'db_area_id' => 6,
            'company_id' => 5,
            'lessee_bl_legal_form_id' => 10,
            'supplier_contractor_id' => 5,
            'supplier_bl_legal_form_id' => 4,
            'bl_customer_request_number' => '0000-000003',
            'bl_customer_request_date' => '2020-01-15 18:55:11',
            'lessee_type' => 0,
            'lessee_name' => 'ООО СТРОЙДОМИНВЕСТ',
            'lessee_second_name' => null,
            'lessee_first_name' => null,
            'lessee_middle_name' => null,
            'lessee_person_phone' => null,
            'lessee_position' => null,
            'lessee_email' => null,
            'lessee_inn' => '4005325352',
            'lessee_kpp' => '517750034',
            'lessee_ogrn' => '7104440032151',
            'lessee_legal_address' => null,
            'lessee_actual_address' => null,
            'lessee_phone' => null,
            'supplier_type' => 0,
            'supplier_name' => 'ГЛОБАЛ ТРАК СЕЙЛС',
            'supplier_second_name' => null,
            'supplier_first_name' => null,
            'supplier_middle_name' => null,
            'supplier_email' => null,
            'supplier_inn' => '3250053353',
            'supplier_kpp' => '773545001',
            'supplier_ogrn' => '1043244001107',
            'supplier_legal_address' => null,
            'supplier_actual_address' => null,
            'supplier_person_phone' => null,
            'supplier_person_FIO' => null,
            'supplier_phone' => null,
            'supplier_position' => null,
            'uid_1c_code' => '0cb377d5-40e6-11ea-a042-708bcda427ce',
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2020-01-15 18:55:11',
            'updated_at' => '2020-01-15 18:55:11',
            'partner_point_id'  => null,
        ]);

        \App\Models\BL\BlCustomerRequest::create([
            'id' => 4,
            'lessee_contractor_id' => 2,
            'bl_status_id' => 11,
            'db_area_id' => 6,
            'company_id' => 5,
            'lessee_bl_legal_form_id' => 15,
            'supplier_contractor_id' => 11,
            'supplier_bl_legal_form_id' => 10,
            'bl_customer_request_number' => '0000-000004',
            'bl_customer_request_date' => '2020-01-15 19:15:15',
            'lessee_type' => 1,
            'lessee_name' => 'Петров П.П.',
            'lessee_second_name' => 'Петров',
            'lessee_first_name' => 'Петр',
            'lessee_middle_name' => 'Петрович',
            'lessee_person_phone' => null,
            'lessee_position' => null,
            'lessee_email' => null,
            'lessee_inn' => '210987654313',
            'lessee_kpp' => null,
            'lessee_ogrn' => null,
            'lessee_legal_address' => null,
            'lessee_actual_address' => null,
            'lessee_phone' => null,
            'supplier_type' => 0,
            'supplier_name' => 'ООО АВТОБУМ',
            'supplier_second_name' => null,
            'supplier_first_name' => null,
            'supplier_middle_name' => null,
            'supplier_email' => null,
            'supplier_inn' => '3530053250',
            'supplier_kpp' => '500351774',
            'supplier_ogrn' => '1071044400321',
            'supplier_legal_address' => null,
            'supplier_actual_address' => null,
            'supplier_person_phone' => null,
            'supplier_person_FIO' => null,
            'supplier_phone' => null,
            'supplier_position' => null,
            'uid_1c_code' => '86e6b876-4107-11ea-a042-708bcda427ce',
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2020-01-15 18:55:11',
            'updated_at' => '2020-01-15 18:55:11',
            'partner_point_id'  => 4,
        ]);

        \App\Models\BL\BlCustomerRequest::create([
            'id' => 5,
            'lessee_contractor_id' => 2,
            'bl_status_id' => 11,
            'db_area_id' => 6,
            'company_id' => 5,
            'lessee_bl_legal_form_id' => 15,
            'supplier_contractor_id' => 4,
            'supplier_bl_legal_form_id' => 10,
            'bl_customer_request_number' => '0000-000005',
            'bl_customer_request_date' => '2020-01-15 19:30:31',
            'lessee_type' => 1,
            'lessee_name' => 'Петров П.П.',
            'lessee_second_name' => 'Петров',
            'lessee_first_name' => 'Петр',
            'lessee_middle_name' => 'Петрович',
            'lessee_person_phone' => null,
            'lessee_position' => null,
            'lessee_email' => null,
            'lessee_inn' => '210987654313',
            'lessee_kpp' => null,
            'lessee_ogrn' => null,
            'lessee_legal_address' => null,
            'lessee_actual_address' => null,
            'lessee_phone' => null,
            'supplier_type' => 0,
            'supplier_name' => 'ООО АВТО-ТОРГ',
            'supplier_second_name' => null,
            'supplier_first_name' => null,
            'supplier_middle_name' => null,
            'supplier_email' => null,
            'supplier_inn' => '6686027702',
            'supplier_kpp' => '667801001',
            'supplier_ogrn' => '1136686021537',
            'supplier_legal_address' => null,
            'supplier_actual_address' => null,
            'supplier_person_phone' => null,
            'supplier_person_FIO' => null,
            'supplier_phone' => null,
            'supplier_position' => null,
            'uid_1c_code' => 'ec66cac5-4281-11ea-a042-708bcda427ce',
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2020-01-15 18:55:11',
            'updated_at' => '2020-01-15 18:55:11',
            'partner_point_id'  => 9,
        ]);

        \App\Models\BL\BlCustomerRequest::create([
            'id' => 6,
            'lessee_contractor_id' => 2,
            'bl_status_id' => 11,
            'db_area_id' => 6,
            'company_id' => 5,
            'lessee_bl_legal_form_id' => 15,
            'supplier_contractor_id' => 4,
            'supplier_bl_legal_form_id' => 10,
            'bl_customer_request_number' => '0000-000006',
            'bl_customer_request_date' => '2020-01-15 20:05:56',
            'lessee_type' => 1,
            'lessee_name' => 'Петров П.П.',
            'lessee_second_name' => 'Петров',
            'lessee_first_name' => 'Петр',
            'lessee_middle_name' => 'Петрович',
            'lessee_person_phone' => null,
            'lessee_position' => null,
            'lessee_email' => null,
            'lessee_inn' => '210987654313',
            'lessee_kpp' => null,
            'lessee_ogrn' => null,
            'lessee_legal_address' => null,
            'lessee_actual_address' => null,
            'lessee_phone' => null,
            'supplier_type' => 0,
            'supplier_name' => 'Audi',
            'supplier_second_name' => null,
            'supplier_first_name' => null,
            'supplier_middle_name' => null,
            'supplier_email' => null,
            'supplier_inn' => '3253530050',
            'supplier_kpp' => '177500354',
            'supplier_ogrn' => null,
            'supplier_legal_address' => null,
            'supplier_actual_address' => null,
            'supplier_person_phone' => null,
            'supplier_person_FIO' => null,
            'supplier_phone' => null,
            'supplier_position' => null,
            'uid_1c_code' => '7bbdb5a5-4285-11ea-a042-708bcda427ce',
            'deleted_l' => 0,
            'created_by' => 'seed',
            'updated_by' => 'seed',
            'created_at' => '2020-01-15 18:55:11',
            'updated_at' => '2020-01-15 18:55:11',
            'partner_point_id'  => 2,
        ]);

        if(config("database.default") == "pgsql"){

            \Illuminate\Support\Facades\DB::statement("SELECT setval('\"public\".\"blCustomerRequests_id_seq\"', 10, true)");
        }
    }
}
